### ISSUE TITLE
Meteor M2 LRPT Images Not Getting Decoded

### ISSUE THREAD

**Issue by MihajloPi** [reynico/raspberry-noaa#41]
I had an issue of Meteor M2 not getting decoded. It seems that PLL never locks onto the signal. I thought I was receiving it on the wrong frequency so I tried both 137.1 MHz and 137.9 MHz with no success. Here's what I get when I read /var/mail/pi:

INFO : Starting rtl_fm record
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 8.70 dB.
Tuner error set to 55 ppm.
Tuned to 138188000 Hz.
Oversampling input by: 4x.
Oversampling output by: 1x.
Buffer size: 7.11ms
Allocating 15 zero-copy buffers
Sampling at 1152000 S/s.
Output at 288000 Hz.
Signal caught, exiting!

User cancel, exiting...
INFO : Normalization in progress
INFO : Demodulation in progress (QPSK)

Meteor-M2 LRPT demodulator v0.3-beta1

(09:17:28) Input: /var/www/wx/meteor/METEOR-M220200920-085954.wav, output: /var/www/wx/meteor/METEOR-M220200920-085954.qpsk
(09:17:28) Input samplerate: 96000
(09:17:28) Demodulator initialized
(09:17:28) (  0.0%) Carrier:   +11.5 Hz, Locked: No
(09:17:33) (  1.2%) Carrier: -2157.8 Hz, Locked: No
(09:17:38) (  2.4%) Carrier: -2832.7 Hz, Locked: No
(09:17:43) (  3.6%) Carrier:  -536.0 Hz, Locked: No
(09:17:48) (  4.8%) Carrier:  -667.9 Hz, Locked: No
(09:17:53) (  6.0%) Carrier: -4422.5 Hz, Locked: No
(09:17:58) (  7.0%) Carrier: -4169.9 Hz, Locked: No
(09:18:03) (  8.0%) Carrier: -4599.0 Hz, Locked: No
(09:18:08) (  9.2%) Carrier:  -671.3 Hz, Locked: No
(09:18:13) ( 10.4%) Carrier:  -513.5 Hz, Locked: No
(09:18:18) ( 11.6%) Carrier: -2522.0 Hz, Locked: No
(09:18:23) ( 12.8%) Carrier: -1324.2 Hz, Locked: No
(09:18:28) ( 14.0%) Carrier: -2388.6 Hz, Locked: No
(09:18:33) ( 15.0%) Carrier:  +112.3 Hz, Locked: No
(09:18:38) ( 16.2%) Carrier:  -158.4 Hz, Locked: No
(09:18:43) ( 17.4%) Carrier: +1937.9 Hz, Locked: No
(09:18:48) ( 18.6%) Carrier:   +10.6 Hz, Locked: No
(09:18:53) ( 19.8%) Carrier: +1878.2 Hz, Locked: No
(09:18:58) ( 21.0%) Carrier:  -839.4 Hz, Locked: No
(09:19:03) ( 22.1%) Carrier:  -993.6 Hz, Locked: No
(09:19:08) ( 23.3%) Carrier:  -399.3 Hz, Locked: No
(09:19:13) ( 24.5%) Carrier:  -516.4 Hz, Locked: No
(09:19:18) ( 25.7%) Carrier:  +799.3 Hz, Locked: No
(09:19:23) ( 26.9%) Carrier: +2602.7 Hz, Locked: No
(09:19:28) ( 28.1%) Carrier: +1001.5 Hz, Locked: No
(09:19:33) ( 29.3%) Carrier:  +597.8 Hz, Locked: No
(09:19:38) ( 30.4%) Carrier:  +760.5 Hz, Locked: No
(09:19:43) ( 31.6%) Carrier: -4658.3 Hz, Locked: No
(09:19:48) ( 32.8%) Carrier: -5737.5 Hz, Locked: No
(09:19:53) ( 34.0%) Carrier: -2052.9 Hz, Locked: No
(09:19:58) ( 35.2%) Carrier: -5972.9 Hz, Locked: No
(09:20:03) ( 36.4%) Carrier: -3243.8 Hz, Locked: No
(09:20:08) ( 37.5%) Carrier: -4552.8 Hz, Locked: No
(09:20:13) ( 38.7%) Carrier:  -250.7 Hz, Locked: No
(09:20:18) ( 39.9%) Carrier:  -776.9 Hz, Locked: No
(09:20:23) ( 41.1%) Carrier:  +853.7 Hz, Locked: No
(09:20:28) ( 42.3%) Carrier:  +689.0 Hz, Locked: No
(09:20:33) ( 43.5%) Carrier:  -564.1 Hz, Locked: No
(09:20:38) ( 44.5%) Carrier: +1111.7 Hz, Locked: No
(09:20:43) ( 45.7%) Carrier:   +22.5 Hz, Locked: No
(09:20:48) ( 46.9%) Carrier: -3083.9 Hz, Locked: No
(09:20:53) ( 48.1%) Carrier:    -7.3 Hz, Locked: No
(09:20:58) ( 49.3%) Carrier:  -765.1 Hz, Locked: No
(09:21:03) ( 50.4%) Carrier:  -944.2 Hz, Locked: No
(09:21:08) ( 51.6%) Carrier:  -237.6 Hz, Locked: No
(09:21:13) ( 52.8%) Carrier:  -577.4 Hz, Locked: No
(09:21:18) ( 54.0%) Carrier:  +129.8 Hz, Locked: No
(09:21:23) ( 55.2%) Carrier: -1005.0 Hz, Locked: No
(09:21:28) ( 56.3%) Carrier:   -65.3 Hz, Locked: No
(09:21:33) ( 57.5%) Carrier:  +136.6 Hz, Locked: No
(09:21:38) ( 58.7%) Carrier:  +479.9 Hz, Locked: No
(09:21:43) ( 59.9%) Carrier:   -46.4 Hz, Locked: No
(09:21:48) ( 61.1%) Carrier: +1633.7 Hz, Locked: No
(09:21:53) ( 62.3%) Carrier: +1124.9 Hz, Locked: No
(09:21:58) ( 63.4%) Carrier:  -636.2 Hz, Locked: No
(09:22:03) ( 64.6%) Carrier:   +15.5 Hz, Locked: No
(09:22:08) ( 65.8%) Carrier: +2072.0 Hz, Locked: No
(09:22:13) ( 67.0%) Carrier: +6343.8 Hz, Locked: No
(09:22:18) ( 68.2%) Carrier: +5460.3 Hz, Locked: No
(09:22:23) ( 69.4%) Carrier: +7179.5 Hz, Locked: No
(09:22:28) ( 70.6%) Carrier: +4698.1 Hz, Locked: No
(09:22:33) ( 71.8%) Carrier: +2696.1 Hz, Locked: No
(09:22:38) ( 73.0%) Carrier:  +840.9 Hz, Locked: No
(09:22:43) ( 74.2%) Carrier: +5440.1 Hz, Locked: No
(09:22:48) ( 75.4%) Carrier: +4073.0 Hz, Locked: No
(09:22:53) ( 76.6%) Carrier: +5682.3 Hz, Locked: No
(09:22:58) ( 77.7%) Carrier: +2844.0 Hz, Locked: No
(09:23:03) ( 78.9%) Carrier: +1383.2 Hz, Locked: No
(09:23:08) ( 80.1%) Carrier: +1799.0 Hz, Locked: No
(09:23:13) ( 81.3%) Carrier: +2055.9 Hz, Locked: No
(09:23:18) ( 82.5%) Carrier: +1336.5 Hz, Locked: No
(09:23:23) ( 83.7%) Carrier:  -250.5 Hz, Locked: No
(09:23:28) ( 84.9%) Carrier: -3344.0 Hz, Locked: No
(09:23:33) ( 86.1%) Carrier: -3969.6 Hz, Locked: No
(09:23:38) ( 87.3%) Carrier: -1007.9 Hz, Locked: No
(09:23:43) ( 88.5%) Carrier:  +410.2 Hz, Locked: No
(09:23:48) ( 89.7%) Carrier:   +21.9 Hz, Locked: No
(09:23:53) ( 90.9%) Carrier:  -211.3 Hz, Locked: No
(09:23:58) ( 92.1%) Carrier: -1648.3 Hz, Locked: No
(09:24:03) ( 93.3%) Carrier: +2160.6 Hz, Locked: No
(09:24:08) ( 94.5%) Carrier: -2901.0 Hz, Locked: No
(09:24:13) ( 95.7%) Carrier: -2410.9 Hz, Locked: No
(09:24:18) ( 96.9%) Carrier:  +396.4 Hz, Locked: No
(09:24:23) ( 98.1%) Carrier: +2888.0 Hz, Locked: No
(09:24:28) ( 99.3%) Carrier: -1386.5 Hz, Locked: No
(09:24:33) Decoding completed
INFO : Deleting audio files
INFO : Decoding in progress (QPSK to BMP)
Reading /var/www/wx/meteor/METEOR-M220200920-085954.qpsk...
 pos=140704523 ( 99.98%) ( 0, 9295,50) sig= -258 rs=(-1,-1,-1,-1) 0C9C03CF
Total:        615.189209
Processing:   0.000007
Correlation:  429.326233
Viterbi:      166.158142
ECC:          18.983896
Remainder:    0.720928
Packets:      6 / 5781
INFO : I got a successful METEOR-M220200920-085954.dec file. Creating false color image
Reading /var/www/wx/meteor/METEOR-M220200920-085954.dec...
 pos=       0 (  0.00%)
 pos=    1024 ( 16.67%)
 pos=    2048 ( 33.33%)
 pos=    3072 ( 50.00%)
 pos=    4096 ( 66.67%)
 pos=    5120 ( 83.33%)

Total:        0.000043
Processing:   0.000002
Correlation:  0.000000
Viterbi:      0.000000
ECC:          0.000000
Remainder:    0.000041
Packets:      6 / 6
convert-im6.q16: unable to open image `/var/www/wx/meteor/METEOR-M220200920-085954-122.bmp': No such file or directory @ error/blob.c/OpenBlob/2874.
convert-im6.q16: no images defined `/var/www/wx/image/2020/09/20/METEOR-M220200920-085954-122.jpg' @ error/convert.c/ConvertImageCommand/3258.
INFO : Rectifying image to adjust aspect ratio
Traceback (most recent call last):
  File "/home/pi/raspberry-noaa/rectify.py", line 121, in <module>
    img = Image.open(sys.argv[1])
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/wx/image/2020/09/20/METEOR-M220200920-085954-122.jpg'
convert-im6.q16: unable to open image `/var/www/wx/image/2020/09/20/METEOR-M220200920-085954-122-rectified.jpg': No such file or directory @ error/blob.c/OpenBlob/2874.
convert-im6.q16: no images defined `/var/www/wx/image/2020/09/20/METEOR-M220200920-085954-122-rectified.jpg' @ error/convert.c/ConvertImageCommand/3258.
INFO : Deleting base image files
rm: cannot remove '/var/www/wx/meteor/METEOR-M220200920-085954-122.bmp': No such file or directory
rm: cannot remove '/var/www/wx/meteor/METEOR-M220200920-085954.bmp': No such file or directory
rm: cannot remove '/var/www/wx/image/2020/09/20/METEOR-M220200920-085954-122.jpg': No such file or directory
INFO : Posting to Twitter
Traceback (most recent call last):
  File "/home/pi/raspberry-noaa/post.py", line 23, in <module>
    res = api.media_upload(filename)
  File "/usr/local/lib/python3.7/dist-packages/tweepy/api.py", line 223, in media_upload
    file_type = imghdr.what(filename)
  File "/usr/lib/python3.7/imghdr.py", line 16, in what
    f = open(file, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/var/www/wx/image/2020/09/20/METEOR-M220200920-085954-122-rectified.jpg'

From pi@raspberrypi Sun Sep 20 09:51:45 2020
Return-path: <pi@raspberrypi>
Envelope-to: pi@raspberrypi
Delivery-date: Sun, 20 Sep 2020 09:51:45 +0200
Received: from pi by raspberrypi with local (Exim 4.92)
        (envelope-from <pi@raspberrypi>)
        id 1kJu8P-0002Dh-F1
        for pi@raspberrypi; Sun, 20 Sep 2020 09:51:45 +0200
Subject: Output from your job      149
To: pi@raspberrypi
Message-Id: <E1kJu8P-0002Dh-F1@raspberrypi>
From: pi@raspberrypi
Date: Sun, 20 Sep 2020 09:51:45 +0200

**Comment by MihajloPi** [comment]
I resolved the issue. It turns out my tweet was actually too long so I just had to delete some characters in order to make it shorter. Now everything works perfectly as expected.
