### ISSUE TITLE
[Error] Multiple errors 

### ISSUE THREAD

**Issue by HZ1SF** [reynico/raspberry-noaa#57]
**Describe the bug**
Hi @reynico, I did a `git checkout -- sun.py` and git `checkout -- receive.sh` last night then `git pull`, and I noticed these errors in mail:

**Screenshots and/or logs**
```
From pi@raspberrypi Wed Nov 11 00:01:04 2020
Return-path: <pi@raspberrypi>
Envelope-to: pi@raspberrypi
Delivery-date: Wed, 11 Nov 2020 00:01:04 +0300
Received: from pi by raspberrypi with local (Exim 4.92)
	(envelope-from <pi@raspberrypi>)
	id 1kcalE-0000Rf-5i
	for pi@raspberrypi; Wed, 11 Nov 2020 00:01:04 +0300
From: root@raspberrypi (Cron Daemon)
To: pi@raspberrypi
Subject: Cron <pi@raspberrypi> /home/pi/raspberry-noaa/schedule.sh
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/pi>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=pi>
Message-Id: <E1kcalE-0000Rf-5i@raspberrypi>
Date: Wed, 11 Nov 2020 00:01:04 +0300

INFO : Pass prediction in progress
INFO : Pass prediction in progress
INFO : Pass is above 30, that is OK for me
METEOR-M2 20201111-075014 90
warning: commands will be executed using /bin/sh
job 428 at Wed Nov 11 07:50:00 2020
/home/pi/raspberry-noaa/schedule_meteor.sh: line 28: sqlite3: command not found
INFO : Pass prediction in progress
INFO : Pass prediction in progress
INFO : Pass prediction in progress
INFO : Pass is above 30, that is OK for me
METEOR-M2 20201111-190349 62
warning: commands will be executed using /bin/sh
job 429 at Wed Nov 11 19:03:00 2020
/home/pi/raspberry-noaa/schedule_meteor.sh: line 28: sqlite3: command not found
INFO : Pass prediction in progress
NOAA19 20201111-054218 35
warning: commands will be executed using /bin/sh
job 430 at Wed Nov 11 05:42:00 2020
/home/pi/raspberry-noaa/schedule_sat.sh: line 34: sqlite3: command not found
NOAA18 20201111-214333 32
warning: commands will be executed using /bin/sh
job 431 at Wed Nov 11 21:43:00 2020
/home/pi/raspberry-noaa/schedule_sat.sh: line 34: sqlite3: command not found
NOAA15 20201111-071545 80
warning: commands will be executed using /bin/sh
job 432 at Wed Nov 11 07:15:00 2020
/home/pi/raspberry-noaa/schedule_sat.sh: line 34: sqlite3: command not found
NOAA15 20201111-182653 53
warning: commands will be executed using /bin/sh
job 433 at Wed Nov 11 18:26:00 2020
/home/pi/raspberry-noaa/schedule_sat.sh: line 34: sqlite3: command not found

From pi@raspberrypi Wed Nov 11 05:58:20 2020
Return-path: <pi@raspberrypi>
Envelope-to: pi@raspberrypi
Delivery-date: Wed, 11 Nov 2020 05:58:20 +0300
Received: from pi by raspberrypi with local (Exim 4.92)
	(envelope-from <pi@raspberrypi>)
	id 1kcgKy-0000hd-3n
	for pi@raspberrypi; Wed, 11 Nov 2020 05:58:20 +0300
Subject: Output from your job      430
To: pi@raspberrypi
Message-Id: <E1kcgKy-0000hd-3n@raspberrypi>
From: pi@raspberrypi
Date: Wed, 11 Nov 2020 05:58:20 +0300

Traceback (most recent call last):
  File "/home/pi/raspberry-noaa/sun.py", line 5, in <module>
    timezone = change_tz + time.localtime().tm_isdst
NameError: name 'change_tz' is not defined
INFO : Starting rtl_fm record
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 49.60 dB.
Tuned to 137580000 Hz.
Oversampling input by: 32x.
Oversampling output by: 1x.
Buffer size: 4.27ms
Sampling at 1920000 S/s.
Output at 60000 Hz.
Signal caught, exiting!

User cancel, exiting...
/home/pi/raspberry-noaa/receive.sh: line 31: [: : integer expression expected
INFO : Bulding pass map
Satellite: NOAA 19
Pass Start: 2020-11-11 02:42:19 UTC
Pass Duration: 15:08
Elevation: 35
Azimuth: 100
Direction: southbound
..INFO : Decoding image
Satellite: NOAA 19
Status: signal processing............................
wxtoimg: warning: Narrow IF bandwidth (set Recording Options/receiver type), low S/N, or volume too high
Gain: 17.7
Channel A: 2 (near infrared)
Channel B: 4 (thermal infrared)
INFO : Decoding image
Satellite: NOAA 19
Status: signal processing............................
wxtoimg: warning: Narrow IF bandwidth (set Recording Options/receiver type), low S/N, or volume too high
Gain: 17.7
Channel A: 2 (near infrared)
Channel B: 4 (thermal infrared)
INFO : Decoding image
Satellite: NOAA 19
Status: signal processing............................
wxtoimg: warning: Narrow IF bandwidth (set Recording Options/receiver type), low S/N, or volume too high
Gain: 17.7
Channel A: 2 (near infrared)
Channel B: 4 (thermal infrared)
/home/pi/raspberry-noaa/receive.sh: line 50: [: : integer expression expected
/home/pi/raspberry-noaa/receive.sh: line 53: sqlite3: command not found
/home/pi/raspberry-noaa/receive.sh: line 56: sqlite3: command not found
/home/pi/raspberry-noaa/receive.sh: line 67: sqlite3: command not found
INFO : Deleting audio files

From pi@raspberrypi Wed Nov 11 07:31:35 2020
Return-path: <pi@raspberrypi>
Envelope-to: pi@raspberrypi
Delivery-date: Wed, 11 Nov 2020 07:31:35 +0300
Received: from pi by raspberrypi with local (Exim 4.92)
	(envelope-from <pi@raspberrypi>)
	id 1kchnD-0000pe-5t
	for pi@raspberrypi; Wed, 11 Nov 2020 07:31:35 +0300
Subject: Output from your job      432
To: pi@raspberrypi
Message-Id: <E1kchnD-0000pe-5t@raspberrypi>
From: pi@raspberrypi
Date: Wed, 11 Nov 2020 07:31:35 +0300

Traceback (most recent call last):
  File "/home/pi/raspberry-noaa/sun.py", line 5, in <module>
    timezone = change_tz + time.localtime().tm_isdst
NameError: name 'change_tz' is not defined
INFO : Starting rtl_fm record
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 49.60 dB.
Tuned to 138100000 Hz.
Oversampling input by: 32x.
Oversampling output by: 1x.
Buffer size: 4.27ms
Sampling at 1920000 S/s.
Output at 60000 Hz.
Signal caught, exiting!

User cancel, exiting...
/home/pi/raspberry-noaa/receive.sh: line 31: [: : integer expression expected
INFO : Bulding pass map
Satellite: NOAA 15
Pass Start: 2020-11-11 04:15:45 UTC
Pass Duration: 15:07
Elevation: 81
Azimuth: 103
Direction: southbound
..INFO : Decoding image
Satellite: NOAA 15
Status: signal processing............................
Gain: 14.1
Channel A: 2 (near infrared)
Channel B: 4 (thermal infrared)
INFO : Decoding image
Satellite: NOAA 15
Status: signal processing............................
Gain: 14.1
Channel A: 2 (near infrared)
Channel B: 4 (thermal infrared)
INFO : Decoding image
Satellite: NOAA 15
Status: signal processing............................
Gain: 14.1
Channel A: 2 (near infrared)
Channel B: 4 (thermal infrared)
/home/pi/raspberry-noaa/receive.sh: line 50: [: : integer expression expected
/home/pi/raspberry-noaa/receive.sh: line 53: sqlite3: command not found
/home/pi/raspberry-noaa/receive.sh: line 56: sqlite3: command not found
/home/pi/raspberry-noaa/receive.sh: line 67: sqlite3: command not found
INFO : Deleting audio files

From pi@raspberrypi Wed Nov 11 07:56:54 2020
Return-path: <pi@raspberrypi>
Envelope-to: pi@raspberrypi
Delivery-date: Wed, 11 Nov 2020 07:56:54 +0300
Received: from pi by raspberrypi with local (Exim 4.92)
	(envelope-from <pi@raspberrypi>)
	id 1kciBi-0000rm-QG
	for pi@raspberrypi; Wed, 11 Nov 2020 07:56:54 +0300
Subject: Output from your job      428
To: pi@raspberrypi
Message-Id: <E1kciBi-0000rm-QG@raspberrypi>
From: pi@raspberrypi
Date: Wed, 11 Nov 2020 07:56:54 +0300

Traceback (most recent call last):
  File "/home/pi/raspberry-noaa/sun.py", line 5, in <module>
    timezone = change_tz + time.localtime().tm_isdst
NameError: name 'change_tz' is not defined
INFO : Starting rtl_fm record
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain set to 48.00 dB.
Tuned to 137388000 Hz.
Oversampling input by: 4x.
Oversampling output by: 1x.
Buffer size: 7.11ms
Sampling at 1152000 S/s.
Output at 288000 Hz.
sox FAIL sox: `/var/ramfs/audio/METEOR-M220201111-075014.wav' error writing output file: No space left on device
Signal caught, exiting!
Signal caught, exiting!

User cancel, exiting...
INFO : Demodulation in progress (QPSK)

Meteor-M2 LRPT demodulator v0.3-beta1

(07:54:35) Input: /var/ramfs/audio/METEOR-M220201111-075014.wav, output: /var/www/wx/meteor/METEOR-M220201111-075014.qpsk
(07:54:35) Input samplerate: 96000
(07:54:35) Demodulator initialized
(07:54:35) (  0.0%) Carrier:   +11.5 Hz, Locked: No
(07:54:40) (  9.0%) Carrier: -6431.9 Hz, Locked: No
(07:54:45) ( 18.1%) Carrier: -1633.1 Hz, Locked: No
(07:54:50) ( 27.2%) Carrier: -5539.2 Hz, Locked: No
(07:54:55) ( 36.2%) Carrier: +3075.5 Hz, Locked: No
(07:55:00) ( 45.3%) Carrier: +3063.2 Hz, Locked: No
(07:55:05) ( 54.4%) Carrier: +3567.4 Hz, Locked: No
(07:55:10) ( 63.4%) Carrier:  +209.5 Hz, Locked: No
(07:55:15) ( 72.5%) Carrier: +3167.5 Hz, Locked: No
(07:55:20) ( 81.6%) Carrier: +2956.6 Hz, Locked: No
(07:55:25) ( 90.6%) Carrier: +2910.6 Hz, Locked: No
(07:55:30) ( 99.7%) Carrier: +2853.3 Hz, Locked: No
(07:55:35) Decoding completed
INFO : Deleting audio files
INFO : Decoding in progress (QPSK to BMP)
Reading /var/www/wx/meteor/METEOR-M220201111-075014.qpsk...
 pos=36132452 ( 91.91%) ( 4,    0,53) sig=  -20 rs=(11,11,10,12) 1DFCCF1A Onboar pos=36853330 ( 93.74%) ( 4, 3573,59) sig=   -2 rs=( 7, 8, 6, 8) 1DFCCF1A Onboar pos=38229548 ( 97.24%) ( 4,    0,54) sig=   11 rs=( 5, 5, 6, 7) 1DFCCF1A Onboar pos=38589982 ( 98.16%) ( 5,    0,55) sig=   28 rs=( 5, 7, 8, 6) 1DFCCFDA Onboar pos=39196188 ( 99.70%) ( 7,    0,55) sig=   62 rs=( 7, 5, 4, 6) 1DFCCF9A Onboar pos=39294492 ( 99.95%) ( 7,    0,55) sig=   60 rs=( 8, 2, 5, 8) 1DFCCF1A 
Total:        77.046219
Processing:   0.073648
Correlation:  42.747913
Viterbi:      28.303690
ECC:          3.058629
Remainder:    2.862336
Packets:      75 / 1655
Elapsed time: 00:00:20.928
/home/pi/raspberry-noaa/receive_meteor.sh: line 63: [: : integer expression expected
INFO : I got a successful METEOR-M220201111-075014.dec file. Creating false color image
Reading /var/www/wx/meteor/METEOR-M220201111-075014.dec...
 pos=       0 (  0.00%) 
 pos=    1024 (  1.33%) 
 pos=    2048 (  2.67%) 
 pos=    3072 (  4.00%) 
 pos=    4096 (  5.33%) 
 pos=    5120 (  6.67%) 
 pos=    6144 (  8.00%) 
 pos=    7168 (  9.33%) 
 pos=    8192 ( 10.67%) 
 pos=    9216 ( 12.00%) 
 pos=   10240 ( 13.33%) Onboard time: 07:54:05.128
 pos=   11264 ( 14.67%) 
 pos=   12288 ( 16.00%) 
 pos=   13312 ( 17.33%) Onboard time: 07:54:10.052
 pos=   14336 ( 18.67%) 
 pos=   15360 ( 20.00%) 
 pos=   16384 ( 21.33%) 
 pos=   17408 ( 22.67%) 
 pos=   18432 ( 24.00%) 
 pos=   19456 ( 25.33%) 
 pos=   20480 ( 26.67%) 
 pos=   21504 ( 28.00%) 
 pos=   22528 ( 29.33%) 
 pos=   23552 ( 30.67%) 
 pos=   24576 ( 32.00%) 
 pos=   25600 ( 33.33%) 
 pos=   26624 ( 34.67%) 
 pos=   27648 ( 36.00%) 
 pos=   28672 ( 37.33%) 
 pos=   29696 ( 38.67%) 
 pos=   30720 ( 40.00%) 
 pos=   31744 ( 41.33%) 
 pos=   32768 ( 42.67%) 
 pos=   33792 ( 44.00%) 
 pos=   34816 ( 45.33%) Onboard time: 07:54:19.900
 pos=   35840 ( 46.67%) 
 pos=   36864 ( 48.00%) 
 pos=   37888 ( 49.33%) 
 pos=   38912 ( 50.67%) Onboard time: 07:54:22.364
 pos=   39936 ( 52.00%) 
 pos=   40960 ( 53.33%) 
 pos=   41984 ( 54.67%) 
 pos=   43008 ( 56.00%) 
 pos=   44032 ( 57.33%) 
 pos=   45056 ( 58.67%) 
 pos=   46080 ( 60.00%) 
 pos=   47104 ( 61.33%) 
 pos=   48128 ( 62.67%) 
 pos=   49152 ( 64.00%) 
 pos=   50176 ( 65.33%) 
 pos=   51200 ( 66.67%) 
 pos=   52224 ( 68.00%) 
 pos=   53248 ( 69.33%) 
 pos=   54272 ( 70.67%) 
 pos=   55296 ( 72.00%) 
 pos=   56320 ( 73.33%) 
 pos=   57344 ( 74.67%) 
 pos=   58368 ( 76.00%) 
 pos=   59392 ( 77.33%) 
 pos=   60416 ( 78.67%) 
 pos=   61440 ( 80.00%) 
 pos=   62464 ( 81.33%) 
 pos=   63488 ( 82.67%) 
 pos=   64512 ( 84.00%) 
 pos=   65536 ( 85.33%) 
 pos=   66560 ( 86.67%) 
 pos=   67584 ( 88.00%) 
 pos=   68608 ( 89.33%) 
 pos=   69632 ( 90.67%) Onboard time: 07:54:26.056
 pos=   70656 ( 92.00%) 
 pos=   71680 ( 93.33%) 
 pos=   72704 ( 94.67%) 
 pos=   73728 ( 96.00%) 
 pos=   74752 ( 97.33%) 
 pos=   75776 ( 98.67%) 

Total:        0.071136
Processing:   0.070668
Correlation:  0.000000
Viterbi:      0.000000
ECC:          0.000000
Remainder:    0.000468
Packets:      75 / 75
Elapsed time: 00:00:20.928
INFO : Rectifying image to adjust aspect ratio
Opened 1568x144 image
Spawning process  1
Spawning process  2
Spawning process  3
Spawning process  4
/home/pi/raspberry-noaa/receive_meteor.sh: line 81: sqlite3: command not found
/home/pi/raspberry-noaa/receive_meteor.sh: line 82: sqlite3: command not found
/home/pi/raspberry-noaa/receive_meteor.sh: line 87: sqlite3: command not found
```

**Server information (please complete the following information):**
 - OS: [Raspbian Buster]
 - Python version [3.7.3]
 - SDR device [Nooelec nesdr Smart]

**Additional context**
No additional context, I just let raspberry-noaa do it's thing

I'm going to reinstall the OS and raspberry-noaa but wanted to let you know about these errors first, if they persist I will let you know

**Comment by reynico** [comment]
Hi saud! I'll close this issue on behalf of #58
